default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: flux_capacitor_development

test:
  <<: *default
  database: flux_capacitor_test

production:
  <<: *default
  database: flux_capacitor_production
